version: "3"
services:
  node-client:
    build: ./
    image: node-client
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
